# Configuration Netlify pour Optima
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Commande de build
  command = "npm run build"

  # Dossier de publication (sortie de Vite)
  publish = "dist"

  # Variables d'environnement pour le build
  # IMPORTANT: Configurez aussi les variables d'environnement dans Netlify UI
  # Site Settings > Environment variables

# Redirection SPA - Toutes les routes vers index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    # Empêche l'affichage dans une iframe
    X-Frame-Options = "DENY"

    # Empêche la détection MIME
    X-Content-Type-Options = "nosniff"

    # Protection XSS
    X-XSS-Protection = "1; mode=block"

    # Politique de référent
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Content Security Policy (peut être ajusté selon vos besoins)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co https://api.themoviedb.org https://graphql.anilist.co"

# Cache pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les icônes
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Pas de cache pour index.html
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Configuration des plugins (optionnel)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
